# action.yml
name: "Docker-Compose Images GHCR Publish"
author: "Ilya Belezyakov"
description: "Publish docker images built from docker-compose file to github packages"
branding:
  icon: "database"
  color: "red"
inputs:
  version:
    description: "Release version (tag)"
    required: false
    default: ''
  docker_compose:
    description: "docker-compose file to build and publish images from"
    required: true
  repo_token:
    description: "Github Repo token"
    required: false
    default: ''
  repo_connect:
    description: "Connect package to current repository"
    type: choice
    required: false
    default: 'true'
    options:
      - true
      - false
outputs:
  tag:
    description: "Tag that was published"
    value: ${{ steps.tag.outputs.semver }}
runs:
  using: "composite"
  steps:
    - id: tag
      run: |
        # if VERSION is not set, get it from git repo
        VERSION="${{ inputs.version }}"
        if [ -z "$VERSION" ]; then
            VERSION=$(${{ github.action_path }}/src/version.sh)
        fi
        echo "VERSION: $VERSION"
        echo "::set-output name=semver::$(echo $VERSION)"
        echo "VERSION=$VERSION" >> $GITHUB_ENV
      shell: bash
    - id: publish
      run: ${{ github.action_path }}/src/publish.sh $VERSION ${{ inputs.docker_compose }} ${{ inputs.repo_token }} ${{ inputs.repo_connect }}
      shell: bash
